version: '3.7'

services:
  api:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
    container_name: motto-api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - rabbitmq
      - minio
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=mottodb;Username=mottouser;Password=mottopassword
      - RABBITMQ_CONNECTION_STRING=amqp://guest:guest@rabbitmq:5672/
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    networks:
      - motto-net

  postgres:
    image: postgres:latest
    container_name: motto-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mottouser
      POSTGRES_PASSWORD: mottopassword
      POSTGRES_DB: mottodb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - motto-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: motto-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - motto-net

  minio:
    image: minio/minio
    container_name: minio
    build:
      context: ./dockerfiles/dockerfile_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopass
    working_dir: "/minio/storage"
    volumes:
      - ./Storage/minio/storage:/minio/storage
    command: server /minio/storage --console-address :9001
    networks:
      - motto-net

networks:
  motto-net:

volumes:
  postgres-data:
  minio-data:
