version: '3.8'

services:
      
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mottouser
      POSTGRES_PASSWORD: mottopassword
      POSTGRES_DB: mottodb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - motto-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - motto-net
    healthcheck:
      test: rabbitmq-diagnostics check_port_listener 5672
      interval: 10s
      timeout: 10s
      retries: 10

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniopass
    working_dir: "/minio/storage"
    volumes:
      - ./Storage/minio/storage:/minio/storage
    command: server /minio/storage --console-address :9001
    networks:
      - motto-net
      
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
    networks:
      - motto-net

networks:
  motto-net:

volumes:
  postgres-data:
  minio-data:
