name: CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Verify Docker installation
      run: |
        docker --version
        docker-compose --version

    - name: Build and run docker-compose
      run: docker-compose up -d --build

    - name: List running Docker containers
      run: docker ps

    - name: Wait for services to be healthy
      run: |
        while ! docker-compose exec -T api curl -sSf http://api:5000/health; do
          echo "Waiting for API to be healthy..."
          sleep 5
        done

    - name: Update database
      run: |
        dotnet tool install --global dotnet-ef
        dotnet tool restore
        dotnet ef database update -c ApplicationDbContext -p entities

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Run tests
      run: dotnet test ./tests -e ASPNETCORE_ENVIRONMENT=Local

    - name: Tear down Docker containers
      run: docker-compose down
